[project]
name = "playfield"
version = "0.1.0"
description = "Playfield"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "apscheduler>=3.11.0",
    "flask>=3.1.0",
    "gunicorn>=23.0.0",
]
